stages:
    - build
    - test
    - build_docker
install_dependencies:
    stage: build
    image: node:latest
    script:
        - cd Angular && npm install 

build docker image:
    stage: build_docker
    image: docker:latest
    services:
        - docker:dind
    script:
        -docker login --username $DOCKER_HUB_USER --password $DOCKER_HUB_TOKEN
        - docker build --rm -t $DOCKER_HUB_USER/GP_Projeto:$CI_COMMIT_SHA -f deploy/Dockerfile Angular
        - docker push $DOCKER_HUB_USER/GP_Projeto:$CI_COMMIT_SHA