
FROM node:latest AS my-app-build

WORKDIR /
COPY package*.json ./

#RUN npm ci
#RUN npm install

#RUN npm run build
RUN npm ci --only=production
RUN npm build

COPY . .

EXPOSE 8080
CMD [ "node", "server.js" ]