
#FROM node:latest AS my-app-build

#WORKDIR /
#COPY package*.json ./

#RUN npm ci --only=production
#RUN npm build

#COPY . .

#EXPOSE 8080
#CMD [ "node", "server.js" ]

FROM node:12

# Create app directory
WORKDIR /

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package*.json ./

RUN npm install
RUN npm install -g @angular/cli@7.3.9

# If you are building your code for production
# RUN npm ci --only=production

# Bundle app source
COPY . .

EXPOSE 8080
CMD [ "node", "server.js" ]